sudo: required
languages: node_js
node_js:
  - "stable"
services:
  - docker

before_install:
  - docker build -t khushbook/docker-react -f Dockerfile.dev .

script:
  - docker run khushbook/docker-react npm run test -- --coverage
